# ---
# config for SpecificationMappingDataset
# dataSetType: SpecificationMappingDataset
# phase:
#   - train
#   - val
# specificationFilePath: data.csv
# test_size_ratio: 0.25
# header:
#   - img_path
#   - label
# ...
---
# config for ImageFolderDataSet
dataSetType: ImageFolderDataSet
phase:
  - train
  - val
directory: data_train_test_dataset
...